[build]
  command = "npm run build || echo 'Build failed'"
  publish = "dist"
  environment = { NODE_VERSION = "16.15.1" } # Match your Node version


[context.production]
  command = "npm run build"  # Ensure the correct build command runs during production deploys

[build.environment]
  NODE_VERSION = "16.15.1"   # Specify your Node.js version; replace with your local version if different

