[build]
  command = "npm run build || echo 'Build failed'"
  publish = "dist"

# Define environment variables
[build.environment]
  NODE_VERSION = "16.15.1" # Specify your Node.js version; replace with your local version if different

[context.production]
  command = "npm run build" # Ensure the correct build command runs during production deploys
